-------------------------------------------------------------------------------
Test set: school.xauat.blog.BlogApplicationTests
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.21 s <<< FAILURE! - in school.xauat.blog.BlogApplicationTests
test  Time elapsed: 3.698 s  <<< ERROR!
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at school.xauat.blog.BlogApplicationTests.test(BlogApplicationTests.java:27)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at school.xauat.blog.BlogApplicationTests.test(BlogApplicationTests.java:27)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused: no further information

